name        : lesspipe
version     : 1.83
release     : 2
source      :
    - http://www-zeuthen.desy.de/~friebel/unix/less/lesspipe.tar.gz : d616f0d51852e60fb0d0801eec9c31b10e0acc6fdfdc62ec46ef7bfd60ce675e
homepage    : http://www-zeuthen.desy.de/~friebel/unix/lesspipe.html
license     : GPL-2.0
component   : system.utils
summary     : Input filter and preprocessor for the pager "less"
description : |
    lesspipe.sh is an input filter for "less" which allows the viewing of binary content, compressed files, and archives.
setup      : |
    ./configure --prefix=/usr --default # Doesn't support almost any of the configure options
build      : |
    %make
install    : |
    %make_install
